// vue2-cli/src-github-search/components/List.vue
<template>
	<div class="row">
		<!-- 展示用户列表 -->
		<div v-show="info.users.length" class="card" v-for="user in info.users" :key="user.login">
			<a :href="user.html_url" target="_blank">
				<img :src="user.avatar_url" style='width: 100px'/>
			</a>
			<p class="card-text">{{user.login}}</p>
		</div>
		<!-- 展示欢迎词 -->
		<h1 v-show="info.isFirst">欢迎使用！</h1>
		<!-- 展示加载中 -->
		<h1 v-show="info.isLoading">加载中....</h1>
		<!-- 展示错误信息 -->
		<h1 v-show="info.errMsg">{{info.errMsg}}</h1>
	</div>
</template>

<script>
	export default {
		name:'List',
		data() {
			return {
				info:{
                    isFirst:true,
                    isLoading:false,
                    errMsg:'',
                    users:[],
                }
			}
		},
		mounted() {
			this.$bus.$on("updateListData",(dataObj)=>{
                // 直接赋值会丢失对象内部的一些属性
                // this.info=dataObj
                // 使用es6的语法展开
                // 后面的对象会更新前面对象中的属性，并且在前面对象有但是后面对象没有的属性会保留
                this.info={...this.info,...dataObj}
                
            })
		},
	}
</script>

<style scoped>
	.album {
		min-height: 50rem; /* Can be removed; just added for demo purposes */
		padding-top: 3rem;
		padding-bottom: 3rem;
		background-color: #f7f7f7;
	}

	.card {
		float: left;
		width: 33.333%;
		padding: .75rem;
		margin-bottom: 2rem;
		border: 1px solid #efefef;
		text-align: center;
	}

	.card > img {
		margin-bottom: .75rem;
		border-radius: 100px;
	}

	.card-text {
		font-size: 85%;
	}
</style>

// react-my-app/src-searchGithub/components/List/List.jsx
import React, { Component } from 'react'
import "./List.css";

export default class List extends Component {

    render() {
        const {users,isFirst, isLoading, errMsg} = this.props.stateObj

        return (
            <div className="row">
                {
                    isFirst? <h1 >欢迎使用！</h1> :
                    isLoading? <h1 >加载中....</h1>:
                    errMsg? <h1 style={{color:"red"}}>{errMsg}</h1> :
                    users.map(user => {
                        return (
                            <div className="card" key={user.id} >
                                <a href={user.html_url}
                                    target="_blank">
                                    <img alt="头像不存在"
                                        src={user.avatar_url}
                                        style={{ width: '100px' }} />
                                </a>
                                <p className="card-text">{user.login}</p>
                            </div>
                        )
                    })
                }
                {/* https://images.pexels.com/photos/620337/pexels-photo-620337.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1 */}
            </div>
        )
    }
}
