// vue2-cli/src-多级嵌套路由/pages/Message.vue
<template>
  <div>
    <ul>
      <li><a href="/message1">messages001</a>&nbsp;&nbsp;</li>
      <li><a href="/message2">messages002</a>&nbsp;&nbsp;</li>
      <li><a href="/message3">messages003</a>&nbsp;&nbsp;</li>
    </ul>
  </div>
</template>

<script>
export default {
    name:"Message",
};
</script>

<style scoped>
</style>

// react-my-app/src/pages/Message/Message.jsx
import React from 'react'

export default function Message() {
    return (
        <div>
            <ul>
                <li><a href="/message1">messages001</a>&nbsp;&nbsp;</li>
                <li><a href="/message2">messages002</a>&nbsp;&nbsp;</li>
                <li><a href="/message3">messages003</a>&nbsp;&nbsp;</li>
            </ul>
        </div>
    )
}
