// vue2-cli/src-vuex/App.vue
<template>
  <div id="app">
    <Count />
    <hr />
    <Person />
  </div>
</template>

<script>
import Count from "./components/Count.vue";
import Person from "./components/Person.vue";

export default {
  name: "App",
  components: {
    Count,
    Person,
  },
  mounted() {
    console.log(this);
  },
};
</script>

<style>
</style>

// react-my-app/src-react-redux多组件通信/App.jsx
import React, { Component } from 'react';
import CountContainer from './containers/Count/Count'
import PersonContainer from './containers/Person/Person'

export default class App extends Component {

  render() {

    return (
      <div>
        <CountContainer />
        <hr/>
        <PersonContainer />
      </div>
    )
  }
}
